### PR TITLE
Azure Stream Analytics example

### PR DESCRIPTION
**Pull request by mikhailshilkov**
An example Pulumi program that deploys an Azure Stream Analytics job to transform data in an Event Hub.

### CODE REVIEW

**Comment by stack72** [comment]
Hey @mikhailshilkov 	

So I can see you listed the inputs, but what do I do with them? Where do I put them and how can I see the outputs?

P.

**Comment by mikhailshilkov** [comment]
@stack72 You need to send events with an Event Hub client, e.g. [ServiceBusExplorer](https://github.com/paolosalvatori/ServiceBusExplorer). 

Once https://github.com/pulumi/pulumi-azure/pull/289 lands, we can easily add an HTTP callback function to send those events from within the stack, if you think that would help.

**Comment by stack72** [comment]
@mikhailshilkov I think it would help people by adding a wee bit of info in the README about what they would still need to do with this sample application is all - I was confused at the start because I don't know these systems. The rest of the example looks good!

**Comment by stack72** [comment]
This looks so much more usable now - that small command has helped a tonne - thanks so much! :)

**Pull request merged**
