### PR TITLE
Requires examples to be explicitly skipped or made into tests on CI

### PR DESCRIPTION
**Pull request by t0yv0**
CI currently does not test all examples, and sometimes examples decay. This PR starts with azure examples only, to start the discussion and test the idea of requiring explicitly skipping examples from CI coverage. Skips are added for all Azure examples that were previously excluded from CI.

Differences from before:

1. When someone adds a new example, the CI will fail requesting they list the example in `azure_tests.go` as either an active test or a skipped test

2. Individual test names have changed slightly, that is now we get looks like this:

```
--- PASS: TestAccAzureTs (0.00s)
    --- SKIP: TestAccAzureTs/azure-ts-aci (0.00s)
    --- SKIP: TestAccAzureTs/azure-ts-aks (0.00s)
    --- SKIP: TestAccAzureTs/azure-ts-aks-helm (0.00s)
    --- SKIP: TestAccAzureTs/azure-ts-cosmosdb-logicapp (0.00s)
    --- SKIP: TestAccAzureTs/azure-ts-functions-many (0.00s)
    --- SKIP: TestAccAzureTs/azure-ts-static-website (0.00s)
    --- SKIP: TestAccAzureTs/azure-ts-synapse (0.00s)
    --- SKIP: TestAccAzureTs/azure-ts-webapp-privateendpoint-vnet-injection (0.00s)
    --- SKIP: TestAccAzureTs/classic-azure-ts-aks-helm (0.00s)
    --- SKIP: TestAccAzureTs/classic-azure-ts-aks-keda (0.00s)
    --- SKIP: TestAccAzureTs/classic-azure-ts-aks-mean (0.00s)
    --- SKIP: TestAccAzureTs/classic-azure-ts-aks-multicluster (0.00s)
    --- SKIP: TestAccAzureTs/classic-azure-ts-aks-with-diagnostics (0.00s)
    --- SKIP: TestAccAzureTs/classic-azure-ts-api-management (0.00s)
    --- SKIP: TestAccAzureTs/classic-azure-ts-appservice-devops (0.00s)
    --- SKIP: TestAccAzureTs/classic-azure-ts-appservice-springboot (0.00s)
    --- SKIP: TestAccAzureTs/classic-azure-ts-cosmosapp-component (0.00s)
    --- SKIP: TestAccAzureTs/classic-azure-ts-dynamicresource (0.00s)
    --- SKIP: TestAccAzureTs/classic-azure-ts-hdinsight-spark (0.00s)
    --- SKIP: TestAccAzureTs/classic-azure-ts-msi-keyvault-rbac (0.00s)
    --- SKIP: TestAccAzureTs/classic-azure-ts-serverless-url-shortener-global (0.00s)
    --- SKIP: TestAccAzureTs/classic-azure-ts-vm-provisioners (0.00s)
    --- SKIP: TestAccAzureTs/classic-azure-ts-webserver-component (0.00s)
    --- PASS: TestAccAzureTs/classic-azure-ts-arm-template (329.66s)
    --- PASS: TestAccAzureTs/classic-azure-ts-stream-analytics (337.82s)
    --- PASS: TestAccAzureTs/azure-ts-appservice (350.45s)
    --- PASS: TestAccAzureTs/azure-ts-appservice-docker (356.43s)
    --- PASS: TestAccAzureTs/azure-ts-functions (357.85s)
    --- PASS: TestAccAzureTs/azure-ts-webserver (462.77s)
    --- PASS: TestAccAzureTs/classic-azure-ts-vm-scaleset (509.67s)
```

### CODE REVIEW

**Comment by t0yv0** [comment]
@mikhailshilkov your pushback in Gdoc on tests taking too long was on point. I tried running auto-detect tests and it was not a pretty picture:

```
--- FAIL: TestAccAzureTs (0.00s)
    --- FAIL: TestAccAzureTs/classic-azure-ts-appservice-springboot (0.00s)  # NEW
    --- FAIL: TestAccAzureTs/classic-azure-ts-appservice-devops (0.00s) # NEW
    --- FAIL: TestAccAzureTs/classic-azure-ts-aks-multicluster (65.80s)  # NEW
    --- FAIL: TestAccAzureTs/classic-azure-ts-aks-keda (192.05s) # NEW
    --- FAIL: TestAccAzureTs/classic-azure-ts-vm-provisioners (230.09s)  # NEW
    --- FAIL: TestAccAzureTs/classic-azure-ts-aks-with-diagnostics (273.64s) # NEW
    --- PASS: TestAccAzureTs/azure-ts-aci (302.61s)
    --- FAIL: TestAccAzureTs/classic-azure-ts-aks-mean (439.04s) # NEW
    --- FAIL: TestAccAzureTs/classic-azure-ts-webserver-component (451.02s) # NEW
    --- FAIL: TestAccAzureTs/azure-ts-functions-many (502.87s) # NEW
    --- PASS: TestAccAzureTs/classic-azure-ts-arm-template (519.69s)
    --- PASS: TestAccAzureTs/classic-azure-ts-stream-analytics (531.02s)
    --- FAIL: TestAccAzureTs/classic-azure-ts-msi-keyvault-rbac (543.49s) # NEW
    --- FAIL: TestAccAzureTs/classic-azure-ts-cosmosapp-component (577.14s) # NEW
    --- PASS: TestAccAzureTs/azure-ts-functions (602.59s)
    --- FAIL: TestAccAzureTs/classic-azure-ts-dynamicresource (606.74s) # NEW
    --- PASS: TestAccAzureTs/classic-azure-ts-vm-scaleset (621.70s)
    --- PASS: TestAccAzureTs/azure-ts-webapp-privateendpoint-vnet-injection (634.56s)
    --- PASS: TestAccAzureTs/azure-ts-appservice-docker (736.38s)
    --- FAIL: TestAccAzureTs/classic-azure-ts-hdinsight-spark (796.16s) # NEW
    --- FAIL: TestAccAzureTs/azure-ts-aks-helm (807.20s) # NEW
    --- FAIL: TestAccAzureTs/classic-azure-ts-aks-helm (817.18s) # NEW
    --- PASS: TestAccAzureTs/azure-ts-static-website (842.86s)
    --- FAIL: TestAccAzureTs/classic-azure-ts-serverless-url-shortener-global (866.34s) # NEW
    --- PASS: TestAccAzureTs/azure-ts-appservice (973.31s)
    --- FAIL: TestAccAzureTs/azure-ts-synapse (987.05s) # NEW
    --- PASS: TestAccAzureTs/azure-ts-webserver (1017.81s)
    --- PASS: TestAccAzureTs/azure-ts-aks (1346.88s)
    --- PASS: TestAccAzureTs/azure-ts-cosmosdb-logicapp (1904.50s)
    --- PASS: TestAccAzureTs/classic-azure-ts-api-management (3320.94s)
```

3320.94s is almost an hour.

So we're balancing automatic coverage and ergonomics here, what other options do we have? Is there an option to mark a slow test to run nightly or weekly and not block a PR?

**Comment by stack72** [comment]
So we have to be super careful here - the examples repo is a bit of a dumping ground for "interesting" projects

Just because it's in the repo, doesn't mean we need to ensure that it's run as a nightly test

There are a lot of code examples in here that take more to run than the benefit would give us

It's more of an opt-in style situation than an opt-out because of this reason

P.

**Comment by t0yv0** [comment]
Ah, interesting. Well I can drop this and we can use the older opt-in behavior if that makes more sense. 

So is the thinking behind it described somewhere? 

I feel like it would be nice to maintain the examples as in know when they break by bit-rot, but given some are more esoteric as you say, nightly is a bit too much feedback. Perhaps just fixing them when breakage is reported is fine, or are there options to run something, weekly? monthly?

The second breakage factor is when an update to something in core pulumi breaks the examples and we might want to know. Are the nightlies opted into as tests currently to give us that particular feedback?  Is there sufficient feedback from other pulumi CIs so that is not an issue?

**Comment by t0yv0** [comment]
Ah well, taking a step back this is perhaps "ain't broke don't fix it situation" :)  I will close for now.

I tried adding the aws-ts-eks-helm example to CI but that is still broken as it awaits the pulumi-kuberenetes release, I'll come back to proposing adding that to CI once that lands, since I read in the tracker it was a popular example.

**Pull request closed without merging**
