### PR TITLE
Update the Go unit test example

### PR DESCRIPTION
**Pull request by mikhailshilkov**
Split out of #615 for faster turnaround

### CODE REVIEW

**Comment by mikhailshilkov** [comment]
> Does this only work in us-east-2 (due to the AMI)? If so should we update the readme?

Well, this is a unit test with mocks, so the test doesn't care about the region as it does not do anything "real" with AWS.

**Comment by EvanBoyle** [comment]
The example is still deployable though no? I guess the readme doesn't specify any instructions on deploying the app.

**Comment by mikhailshilkov** [comment]
It hopefully is, but I focused README's of all unit tests on simply running the tests. If you think we should improve that, do you mind opening a separate issue? I don't think I can get to this today. Thanks!

**Comment by mikhailshilkov** [comment]
Merging as this example has no effect on the build

**Pull request merged**
