### PR TITLE
Add Python GCP Cloud Run example

### PR DESCRIPTION
**Pull request by pavelkraleu**
This example shows how how to setup **Cloud Run** deployment with **Cloud SQL** database and how to connecto to it.

It took me some time to realize that annotation `run.googleapis.com/cloudsql-instances` is needed in order to be Cloud SQL reachable from Cloud Run

### CODE REVIEW

**Comment by stack72** [comment]
Hey @pavelkraleu 

Thanks for the work here. When I jsut tried to run this example, I got the following:

```
Diagnostics:
  pulumi:pulumi:Stack (gcp-py-cloudrun-cloudsql-dev):
    error: update failed

  gcp:cloudrun:Service (default-service):
    error: 1 error occurred:
    	* Error creating Service: googleapi: got HTTP response code 404 with body: <!DOCTYPE html>
    <html lang=en>
      <meta charset=utf-8>
      <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
      <title>Error 404 (Not Found)!!1</title>
      <style>
        *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
      </style>
      <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
      <p><b>404.</b> <ins>That’s an error.</ins>
      <p>The requested URL <code>/apis/serving.knative.dev/v1/namespaces/pulumi-ci-gcp-provider/services</code> was not found on this server.  <ins>That’s all we know.</ins>

```

My config is as follows:

```
config:
  gcp-py-cloudrun-cloudsql:db-name: project-db
  gcp-py-cloudrun-cloudsql:db-password:
    secure: AAABAIdpHKdFWjDy0ZTWinZtjgrDE8vXSb//X9PRmlsT8j6BanHvZZKdmw4XAqf8ktM=
  gcp:project: pulumi-ci-gcp-provider
  gcp:zone: us-west1-a
```

Any thoughts here?

**Comment by pavelkraleu** [comment]
Hi @stack72 thank you for looking into that.

I did try to use region you have used and it also fails, but with with different error `Error 400: Invalid request: Invalid value for region: us-west1-a.` The process sucseeds with `us-west1`.

Also, are you sure you are using correct GCP project ID you have access to?

**Comment by stack72** [comment]
@pavelkraleu 

my bad here - CloudRun isnt supported in us-west1 so I changed to europe-west1 and all looks good! thank you so much for the PR here. I also made 1 change locally - I renamed zone to be region, technically `europe-west1` is a region not a zone - I think that's what I was confused about 🗡️ 

I am going to merge this locally and push

Thanks again

Paul

**Comment by pavelkraleu** [comment]
Thank you @stack72 !

**Pull request merged**
