### PR TITLE
Added gcp-go-functions

### PR DESCRIPTION
**Pull request by tasiah**
This example is very similar to #554 except with deployment code written in Go. For #442.

### CODE REVIEW

**Comment by stack72** [comment]
Hey @tasiah 

This looks ace! There are 2 missing things from this example (and 1 of them is missing in #554)

* `dep ensure` to satisfy the dependencies
* `go build .` before the pulumi up

Apart from that, I just took it for a test drive and it looks great!

```

```

**Comment by lukehoban** [comment]
> `go build .` before the pulumi up

This is not needed (anymore) as of https://github.com/pulumi/pulumi/pull/3503, and should no longer be our default guidance for users.  I do not believe docs have been updated yet to reflect this.

**Comment by stack72** [comment]
👍 ooohhh that's awesome

**Comment by stack72** [comment]
@tasiah this is still missing the entry in the README for `dep update`

P.

**Comment by tasiah** [comment]
@stack72 I tested it locally and it worked as expected even though I never ran `dep ensure`. Should I still include it?

**Comment by stack72** [comment]
ah interesting... let's leave it for now - I guess we will need to update the other Go READMEs to remove it if it's in there :)

**Comment by lukehoban** [comment]
`dep ensure` will definitely be needed in the general case. Without it you will pick up whatever happens to be in your GOPATH (and will have to `go get` it there if you haven’t yet) and references wont be versioned. 

Would definitely encourage adding this consistently to examples for now as it is necessary to use these from a clean slate.

**Pull request merged**
