### PR TITLE
Update Python examples to use fn_output forms where appropriate

### PR DESCRIPTION
**Pull request by t0yv0**
Context: pulumi/pulumi#7948

Updates Python examples to use $fn_output feature.

### CODE REVIEW

**Comment by t0yv0** [comment]
Completed eye-balling all Python examples ```Py   67/67``` - since human error is possible, could have omitted something.

This will need a fresh look. Also I am thinking that we should fix pulumi/pulumi#8172 as a pre-requisite and fix the code to use direct calls and no workarounds. In a lot of the places 8172 is a show-stopper.

**Comment by t0yv0** [comment]
pulumi/pulumi#8172 fixed. Previous CI failures were hitting it. Let's see it if passes this time.

**Comment by t0yv0** [comment]
CI failure indicating pulumi/pulumi#8172 has not rolled out to pulumi-azure-native yet.

**Comment by t0yv0** [comment]
The fix is rolled out and we have a ✅  PTAL.

**Review by justinvp — APPROVED** [review]

**Pull request merged**
