### PR TITLE
Cleanup and remove duplicate variable

### PR DESCRIPTION
**Pull request by jandom**
- pulumi_vpc_id is the same as pulumi_vpc

### CODE REVIEW

**Review by pierskarsenbarg — APPROVED** [review]

**Comment by jandom** [comment]
The failing tests seems related to incorrect credentials, don't think this will ever work for external contributions such a this 

> Error: Credentials could not be loaded, please check your action inputs: Could not load credentials from any providers

**Review by stack72 — APPROVED** [review]
Thanks so much for spotting this!

**Comment by stack72** [comment]
@jandom that Credentials issue is because of a small bug in my GHA conditional :/ thanks for spotting that!

**Comment by jandom** [comment]
Many thanks @stack72 – this was such a quick and easy PR!

**Pull request merged**
