### PR TITLE
(bug)use map string instead of map

### PR DESCRIPTION
**Pull request by ranjib**

### CODE REVIEW

**Comment by jaxxstorm** [comment]
Thankyou for the fix!

**Comment by lukehoban** [comment]
Does this code compile?  I would have expected this to need to be `pulumi.StringMap` (not `MapString`: https://pkg.go.dev/github.com/pulumi/pulumi/sdk/v2/go/pulumi#StringMap

**Comment by ranjib** [comment]
Yes. Without this I was hitting compilation errors

**Pull request merged**
