### PR TITLE
upgrade pulumi/pulumi dependencies

### PR DESCRIPTION
**Pull request by tgummerer**
This repo is currently using old pulumi/pkg and pulumi/sdk dependencies.  These depend on the no longer existing appdash-data package, so the tests are currently broken in CI.

Update the dependencies to unbreak CI.

### CODE REVIEW

**Comment by tgummerer** [comment]
pulumi-trace-tool also need its dependencies updated, so I'm converting this to a draft for now.

**Comment by tgummerer** [comment]
Turns out we still need to wait for the pulumi 3.100 release, as 3.99 still has a dependency on pulumi-java that has an older dependency on pulumi/pulumi.

**Comment by cnunciato** [comment]
@tgummerer I went ahead and addressed this with #1538 to unblock the tests, so I think we can close this for now. Thanks for submitting though!

**Comment by tgummerer** [comment]
Great, thanks!

**Pull request closed without merging**
