### PR TITLE
Pin pulumi-command in aws-py-ec2-provisioners

### PR DESCRIPTION
**Pull request by mnlumi**
Related to https://github.com/pulumi/examples/issues/1491

### CODE REVIEW

**Comment by iwahbe** [comment]
In addition to pinning pulumi-command, can you please open in issue in pulumi-command explaining the break?

**Review by scottslowe — APPROVED** [review]

**Comment by scottslowe** [comment]
@mnlumi @iwahbe If we can get the merge conflicts resolved, is there any reason not to merge this?

**Comment by scottslowe** [comment]
I think we may need to close this in favor of #1497 (which doesn't require pinning the Command provider)

**Comment by scottslowe** [comment]
Closing this in favor of #1497

**Pull request closed without merging**
