### PR TITLE
Updated azure function example in javascript

### PR DESCRIPTION
**Pull request by aydrian**
Updated existing `azure-ts-functions` example to use `@pulumi/azure-serverless` package in plain javascript.

### CODE REVIEW

**Comment by mikhailshilkov** [comment]
I would keep it in TS, see #285

**Comment by aydrian** [comment]
It's not a replacement. It's to supplement. It's fine to have them side-by-side. While TypeScript adoption is growing, not everyone knows it.

**Comment by justinvp** [comment]
@aydrian, what's the status of this PR?

**Comment by mikhailshilkov** [comment]
At this point, the original TypeScript example is out-of-date, so there's no point to add a similar JS example. There is https://github.com/pulumi/pulumi-azure/issues/261 to track this, so I'll close this PR for now.

**Pull request closed without merging**
