### PR TITLE
Update Azure Native examples to v2.1.1

### PR DESCRIPTION
**Pull request by mnlumi**

### CODE REVIEW

**Comment by mnlumi** [comment]
@cnunciato Would you be able review these updates? I've taken in the latest fixes for tests, there are still a few failing.

**Comment by lukehoban** [comment]
I believe there are two issues across the failing examples:

>   azure-native:insights:Component (ai):
    error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="Cannot set LogAnalytics as IngestionMode on current api-version" InnerError={"trace":["System.ArgumentException"]}
    
Sounds like a legitimate issue that needs to be fixed.

>   azure:lb:Rule (lbnatrule-http):
    error: deleting urn:pulumi:p-it-fv-az1230--classic-az-c4ac5288::azure-ts-vm-scaleset::azure:lb/rule:Rule::lbnatrule-http: 1 error occurred:
    	* waiting for completion of Load Balancer "lba38cbe08" (Resource Group "vmss-rg5eeda2c8"): Code="NotFound" Message="Resource /subscriptions/***/resourceGroups//providers/Microsoft.Compute/tenants/38DF66CC-83A1-4EDF-A462-24DA3E8114E1 not found." Details=[]
    	
Less clear what is happening here.  Are you able to reproduce this issue locally in the TestAccAzureTsVmScaleset example?

**Comment by scottslowe** [comment]
WRT to the first failure @lukehoban identified (the error with `azure-native:insights:Component`, it looks like we just need to specify the ingestion mode. Unfortunately, the API reference page (https://www.pulumi.com/registry/packages/azure-native/api-docs/insights/component/) doesn't provide _any_ details on ingestion mode (that supporting type is blank/missing details).

**Comment by mnlumi** [comment]
Opened https://github.com/pulumi/pulumi-azure-native/issues/2627 for the api-docs.

**Comment by mnlumi** [comment]
@cnunciato @scottslowe All of the tests are passing 🎉

**Review by cnunciato — APPROVED** [review]

**Comment by mnlumi** [comment]
Resolves https://github.com/pulumi/examples/issues/1437

**Pull request merged**
