### PR TITLE
Add `virtualenv` option to Python examples

### LINKED ISSUE #760: Update all Python examples to have the `virtualenv` option already specified in Pulumi.yaml
And update README instructions as appropriate.

When running `pulumi preview` or `pulumi up`, if the virtual environment directory doesn't exist, an error is returned with the commands to run to create the virtual environment. But with https://github.com/pulumi/pulumi/issues/5164, we would handle the virtual environment creation automatically/transparently so the user would not have to run any additional commands.

### PR DESCRIPTION
**Pull request by lukehoban**
Use the automatically managed `virtualenv: venv` support in all Python examples.

See https://www.pulumi.com/docs/intro/languages/python/#virtual-environments.

Fixes #760.

### CODE REVIEW

**Comment by lukehoban** [comment]
@justinvp You noted in #760 that we should also remove the README sections that suggest running virtualenv commands. Curious your thoughts on whether it's still a good idea to remove those as well?

**Comment by stack72** [comment]
@lukehoban we need to update the go test code as well

```
error: failed to discover plugin requirements: The 'virtualenv' option in Pulumi.yaml is set to "venv", but "/tmp/p-it-fv-az148-2-digitaloce-5da82d26-517438308/venv" doesn't exist; run the following commands to create the virtual environment and install dependencies into it:
```

we need to set `UseAutomaticVirtualEnv: true` in each of the Test funcs that are changed (and relate to a test func)

**Comment by justinvp** [comment]
> @justinvp You noted in #760 that we should also remove the README sections that suggest running virtualenv commands. Curious your thoughts on whether it's still a good idea to remove those as well?

Yes, we should edit those out of the READMEs.

> we need to set `UseAutomaticVirtualEnv: true` in each of the Test funcs that are changed (and relate to a test func)

Yep.

@lukehoban, I can take care of these, if you'd like. I'll push to your branch.

**Review by stack72 — APPROVED** [review]
This is awesome! Thank you both!!

**Pull request merged**
