### PR TITLE
Added secret manager example

### PR DESCRIPTION
**Pull request by pierskarsenbarg**

### CODE REVIEW

**Review by stack72 — APPROVED** [review]

**Comment by stack72** [comment]
t'would be awesome to have this covered in all languages @pierskarsenbarg ;)

**Comment by stack72** [comment]
@pierskarsenbarg any chance you can rebase this and open an issue so we can track adding this in all languages?

**Comment by stack72** [comment]
ping @pierskarsenbarg

**Comment by pierskarsenbarg** [comment]
On it

**Pull request merged**
