### PR TITLE
Remove redundant config prefixes

### LINKED ISSUE #324: minor documentation (or project name) correction for azure-ts-appservice-devops
In the pulumi.yaml, the name is specified as `azure-appservice`

while the documentation uses the name of `azure-appservice-devops`:

6. Define SQL Server username:

pulumi config set azure-appservice-devops:sqlUsername <value>

7. Define SQL Server password (make it complex enough to satisfy Azure policy):

pulumi config set --secret azure-appservice-devops:sqlPassword <value>

### PR DESCRIPTION
**Pull request by mikhailshilkov**
Fixes #324

### CODE REVIEW

**Comment by stack72** [comment]
@mikhailshilkov if you ran this example, can you paste the output of it (minus your permalink) to this PR :)

**Comment by mikhailshilkov** [comment]
@stack72 I only changed `md` and `yaml` files in two examples. Do you still want the output? (of both?)

**Comment by stack72** [comment]
Nah it's fine - thanks!

**Comment by stack72** [comment]
FYI, this LGTM!! Thanks so much @mikhailshilkov 

```
▶ pulumi up --yes
Previewing update (dev):

     Type                            Name                  Plan
 +   pulumi:pulumi:Stack             azure-appservice-dev  create
 +   ├─ azure:core:ResourceGroup     dev-rg                create
 +   ├─ azure:storage:Account        devsa                 create
 +   ├─ azure:appinsights:Insights   dev-ai                create
 +   ├─ azure:appservice:Plan        dev-asp               create
 +   ├─ azure:sql:SqlServer          dev-sql               create
 +   ├─ azure:storage:Container      dev-c                 create
 +   ├─ azure:sql:Database           dev-db                create
 +   ├─ azure:storage:ZipBlob        dev-b                 create
 +   └─ azure:appservice:AppService  dev-as                create

Resources:
    + 10 to create

Updating (dev):

     Type                            Name                  Status
 +   pulumi:pulumi:Stack             azure-appservice-dev  created
 +   ├─ azure:core:ResourceGroup     dev-rg                created
 +   ├─ azure:appinsights:Insights   dev-ai                created
 +   ├─ azure:appservice:Plan        dev-asp               created
 +   ├─ azure:storage:Account        devsa                 created
 +   ├─ azure:sql:SqlServer          dev-sql               created
 +   ├─ azure:storage:Container      dev-c                 created
 +   ├─ azure:storage:ZipBlob        dev-b                 created
 +   ├─ azure:sql:Database           dev-db                created
 +   ├─ azure:appservice:AppService  dev-as                created
 +   ├─ azure:sql:FirewallRule       FR13.77.137.190       created
 +   ├─ azure:sql:FirewallRule       FR13.77.164.91        created
 +   ├─ azure:sql:FirewallRule       FR13.77.153.221       created
 +   ├─ azure:sql:FirewallRule       FR13.66.241.134       created
 +   └─ azure:sql:FirewallRule       FR52.175.194.87       created

Resources:
    + 15 created

Duration: 2m59s

```

Screen Shot 2019-06-21 at 23 55 12

**Pull request merged**
