### PR TITLE
Update GCP GKE example

### PR DESCRIPTION
**Pull request by runlevel5**
## What

Replace default node pool with a new separately managed node pool resource

## Why

Using a non-default node pool is highly recommended practice.

### CODE REVIEW

**Comment by stack72** [comment]
Thanks so much for the work here - you are correct - this is a way better thing to do - would you be interested in updating the PR to do the same thing on the other GKE clusters? 🥇

**Comment by runlevel5** [comment]
@stack72 I've amended the PR

**Comment by stack72** [comment]
Thanks so much @runlevel5 

Giving this a shot right now

**Comment by stack72** [comment]
Hi @runlevel5 

I just tested this locally and all works - I am going to make 1 change before merging though

I see, from the tests, that the kubernetes namespace and service etc get deployed before the NodePool has finished being created so I am going to add a dependsOn to the kubernetes resources to ensure the NodePool is created first

Paul

**Pull request merged**
