### PR TITLE
Repro 6004

### PR DESCRIPTION
**Pull request by t0yv0**
Ref pulumi/pulumi#6004

### CODE REVIEW

**Comment by mikhailshilkov** [comment]
👍

**Comment by t0yv0** [comment]
```
I0330 16:12:02.469989   67663 eventsink.go:59] Error reading resource group "/subscriptions/_/resourceGroups/linuxrgebbe2009" - removing from state


I0330 17:55:23.656850   10870 host_server.go:101] Error reading resource group "/subscriptions/_/resourceGroups/linuxrgebbe2009" - removing from state
I0330 17:55:23.656881   10870 host_server.go:101] eventSink::Debug(<{%reset%}>Error reading resource group "/subscriptions/_/resourceGroups/linuxrgebbe2009" - removing from state<{%reset%}>)

I0330 17:55:23.657512   10870 deployment_executor.go:244] deploymentExecutor.Execute(...): error handling event: unexpected unknown property value
I0330 17:55:23.657542   10870 deployment_executor.go:112] eventSink::Error(<{%reset%}>unexpected unknown property value<{%reset%}>)

I0330 17:55:04.668810   10870 step_generator.go:458] Planner decided not to update 'urn:pulumi:dev::azure-functions-raw::pulumi:pulumi:Stack::azure-functions-raw-dev' after diff (same) (inputs=map[])
I0330 17:55:05.523437   10870 step_generator.go:458] Planner decided not to update 'urn:pulumi:dev::azure-functions-raw::pulumi:providers:azure::default_3_52_1' after diff (same) (inputs=map[location:{westus} version:{3.52.1}])
I0330 17:55:13.567147   10870 step_generator.go:458] Planner decided not to update 'urn:pulumi:dev::azure-functions-raw::azure:core/resourceGroup:ResourceGroup::linuxrg' after diff (same) (inputs=map[__defaults:{[{location} {name}]} location:{westus} name:{linuxrgebbe2009}])
I0330 17:55:13.714547   10870 step_generator.go:560] Planner decided to replace 'urn:pulumi:dev::azure-functions-raw::azure:appservice/plan:Plan::linux-asp' (oldprops=map[__defaults:{[{location} {name}]} kind:{Linux} location:{westus} name:{linux-asp256b863a} reserved:{true} resourceGroupName:{linuxrgebbe2009} sku:{map[__defaults:{[]} size:{Y1} tier:{Dynamic}]}] inputs=map[__defaults:{[{location} {name}]} kind:{Linux} location:output<string>{} name:{linux-aspe6c0e44c} reserved:{true} resourceGroupName:{linuxrgebbe2009} sku:{map[__defaults:{[]} size:{Y1} tier:{Dynamic}]}])
I0330 17:55:13.762161   10870 step_generator.go:696] Planner decided to delete 'urn:pulumi:dev::azure-functions-raw::azure:appservice/plan:Plan::linux-asp' due to replacement
I0330 17:55:15.299251   10870 step_generator.go:458] Planner decided not to update 'urn:pulumi:dev::azure-functions-raw::pulumi:pulumi:Stack::azure-functions-raw-dev' after diff (same) (inputs=map[])
I0330 17:55:16.106114   10870 step_generator.go:458] Planner decided not to update 'urn:pulumi:dev::azure-functions-raw::pulumi:providers:azure::default_3_52_1' after diff (same) (inputs=map[location:{westus} version:{3.52.1}])
I0330 17:55:23.514853   10870 step_generator.go:458] Planner decided not to update 'urn:pulumi:dev::azure-functions-raw::azure:core/resourceGroup:ResourceGroup::linuxrg' after diff (same) (inputs=map[__defaults:{[{location} {name}]} location:{westus} name:{linuxrgebbe2009}])

```

**Comment by t0yv0** [comment]
I am trying to piece together the V9 verbose logs. And learn the engine working as part of this:

1. it decides not to update the resource group
2. it decides to replace Plan::linux-asp
3. somehow, it then decides to query the resource group state from Azure 
4. it swallows a 404 not found error and does "removing from state"
5. somehow later on we get "Unexpected unknown property value"

Is there an env var that will give me more traces from the Azure provider?

I also am noticing the the stack frames from the traces are all misleading as they point to logger helper functions not originators of the trace, will link a PR to fix shortly.

**Comment by mikhailshilkov** [comment]
> somehow, it then decides to query the resource group state from Azure

It's this TF data source invoke: https://github.com/pulumi/pulumi-azure/blob/master/provider/resource.go#L2373

> Is there an env var that will give me more traces from the Azure provider?

try TF_LOG=DEBUG to see what TF does

**Comment by t0yv0** [comment]
https://github.com/pulumi/pulumi/pull/6668 PR to try to fix stack traces reported in the log.

I'm switching to something else to help Komal, TBC..

**Comment by t0yv0** [comment]
I have finally found where "removing from state" message comes from. It is from https://github.com/pulumi/terraform-provider-azurerm/blob/master/azurerm/resource_arm_resource_group.go#L103

**Comment by t0yv0** [comment]
Ok I finally understand your comment Mikhail. Let me add some tracing around that place in tf provider and see if that's indeed where the refresh is coming from.

**Pull request closed without merging**
